datasets:
  feature_face_caption:
    data_type: images
    
    build_info:
      image_path: /home/project/Dataset/Emotion/MER2023/mybuild/dataset-release/dataset-process/video

      # ann_path: /home/project/Dataset/Emotion/MER2023/relative_train_NCEV.txt
      # ann_path: /home/project/Dataset/Emotion/MER2023/MERR_coarse_grained.txt
      # Stage 1
      # ann_path: /home/project/Dataset/Emotion/MER2023/MER2023_pseudo_label.txt
      # Stage 2
      ann_path: /home/project/Dataset/Emotion/MER2023/MERR_fine_grained.txt
