datasets:
  mer2024_caption:
    data_type: images
    
    build_info:
      image_path: /home/project/Dataset/Emotion/MER2024/video-unlabeled-with-test2noise
      ann_path: /home/project/Dataset/Emotion/MER2024/MER2024_noise_pseu_label_8348.txt
